version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.10-node
      - image: circleci/postgres:10
      - image: circleci/redis:5

    working_directory: ~/repo
    steps:
      - checkout

      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
